matrix:
  include:
    - name: "Standard Tests, Doctests, Linting - Python 3.7.1 on Xenial Linux"
      language: python
      python: 3.7
      dist: xenial
      sudo: true
      install:
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install -y python3.7-dev npm solc
        - npm -g install ganache-cli
        - python -m pip install tox
      script: tox

notifications:
  email: false
